### ISSUE TITLE
Why _dense3d_to_sparse function expects the same sparsity pattern over the batch dimension?

### ISSUE THREAD

**Issue by zihanlalala** [facebookresearch/xformers#340]
# ❓ Questions and Help
What if different samples in a batch have different mask patterns? For example, the key padding mask. How can I convert such mask into sparse tensor or what can I do to speed up the training if such mask tensor is sparse enough?

In file xformers/sparse/utils.py, the _dense3d_to_sparse function only accepts mask tensor with same sparsity pattern over the batch dimension.
```
def _dense3d_to_sparse(matrix, device):
    assert len(matrix.shape) == 3
    mask = matrix != 0
    if not torch.all(mask == mask[0]):
        raise ValueError("Expected the same sparsity pattern over the batch dimension")

    # for now, our kernels assume that we have the number of
    # nnz to be divisible by 4
    mask = _round_nnz(mask[0], divisible_by=4)
    mask = mask[None].expand(matrix.shape)

    values = matrix[mask].reshape(matrix.shape[0], -1).to(device)
    row_indices, row_offsets, column_indices = _nonzero_mask_to_sparse_csr_indices(
        mask[0], device
    )
    return values, row_indices, row_offsets, column_indices
```

**Comment by blefaudeux** [comment]
Hey @zihanlalala thanks for the issue, it's a good question ! top of head it's a shortcut in the current kernels, because typically used in vision (Swin for linstance) where the pattern is independent of the position in the batch. I think that it could be extended, short handed at the moment personally but I don't think that there's a fundamental limitation. cc @fmassa and @dianaml0 , I'm actually not sure whether more recent takes also share this limitation or not.

**Comment by fmassa** [comment]
Hi,

This is currently just a limitations in our sparse kernels as @blefaudeux mentioned. So far they assume that the sparsity pattern is the same across all heads / batch dimension, but this is something that we want to fix in the future

**Comment by zihanlalala** [comment]
Thank you and hope for the new feature!
