### ISSUE TITLE
"generated with LTO version 12.0 instead of the expected 11.3"

### ISSUE THREAD

**Issue by 40percentgit** [facebookresearch/xformers#493]
Trying to build on Arch, I was able to a few days ago but now I can't.

I get this issue trying to build _any_ version of xformers, GCC and the cuda-toolkit are at their newest versions.

```
lto1: fatal error: bytecode stream in file ‘/home/[user]/stable-diffusion-webui/repositories/xformers/build/temp.linux-x86_64-cpython-310/home/[user]/stable-diffusion-webui/repositories/xformers/xformers/components/attention/csrc/attention.o’ generated with LTO version 12.0 instead of the expected 11.3
        compilation terminated.
        lto-wrapper: fatal error: /opt/cuda/bin/g++ returned 1 exit status
        compilation terminated.
        /usr/bin/ld: error: lto-wrapper failed
        collect2: error: ld returned 1 exit status
        error: command '/opt/cuda/bin/g++' failed with exit code 1
        [end of output]

```

I can't get any newer versions of the cuda-toolkit or gcc, as they don't exist yet?
```
>gcc --version && g++ --version

gcc (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Looking around the internet says that I need to have the same version of LTO in my GCC, but this version literally doesn't exist on the aur...
I don't know how to fix this, and no one else has had the problem yet... Versions of xformers I know I have compiled in the past do not build anymore, every version gets this error. What can I do?

**Comment by danthe3rd** [comment]
Hi @40percentgit 

Which version of CUDA do you have? (`nvcc --version`)
This error is quite weird - it looks like multiple different compilers are used to compile the source code. Maybe removing the `build` directory and restarting from scratch can help?

**Comment by 40percentgit** [comment]
```
> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```
Should I try to get a newer version from a different source? I have it installed from the AUR, but the nvidia website doesn't present an Arch option in the downloads. It wasn't updated recently, so suddenly not being able to build old versions of xformers is strange.

I've deleted build, recloned the git (taking care to update submodules), started a fresh pip environment, tried older versions of the module, some different branches even, no dice.

**Comment by danthe3rd** [comment]
The latest version of gcc is 12, and you have version 11.3.
From the error "generated with LTO version 12.0 instead of the expected 11.3" it looks like you might have version 12.0 used to compile parts of the things.

If you are building with ninja (which we recommend because it's faster), you can check the host compiler and nvcc compiler path, eg:

```bash
$ head -n5 build/temp*/build.ninja
ninja_required_version = 1.3
cxx = c++
nvcc = /usr/local/cuda-11.6/bin/nvcc
```

**Comment by 40percentgit** [comment]
So I found out that the cuda installation was linking to `/usr/bin/gcc-11`, while the standard `/usr/bin/gcc` is indeed version 12. Turns out some part of the install was using this version as opposed to the one in the cuda installation. I ran `export CC=/usr/bin/gcc-11` and `export  CXX=/usr/bin/g++-11` and the install ran without any problem.

As I'm on Arch (rolling, updated frequently), gcc is newer than the cuda toolkit's version. _For some reason, the cuda version still had priority in $PATH_, and was intercepting the `gcc --version` command, making troubleshooting difficult. I discovered this after running `where gcc`.

I'm not sure how this could be accounted for automatically in an install, but it would be good to post my steps for anyone else having this outlandish issue.

**Comment by gleb-akhmerov** [comment]
Yes, seems to be an issue with the `$PATH`. Since cuda on Arch installs in `/opt/cuda`, it's not on the `$PATH` by default, so it's [suggested on the wiki](https://wiki.archlinux.org/title/GPGPU#Development_3) to add it to the path manually.

It works now, when I set the path like this: `PATH="$PATH:/opt/cuda/bin"`.
It didn't work like this: `PATH="/opt/cuda/bin:$PATH"`.

By the way, for me the error triggered only when using ninja as suggested [here](https://github.com/facebookresearch/xformers/tree/814314dfc207836839c57613c0354fef6e07fa2d#installing-xformers). Without it, xformers compiled fine even with the wrong `$PATH`. Now everything works with or without ninja.
