### ISSUE TITLE
causal mask in Nystromformer

### ISSUE THREAD

**Issue by yuzhenmao** [facebookresearch/xformers#751]
# ❓ Questions and Help
Hi there,

I have a question regarding the implementation of the causal mask in Nystromformer. In https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/nystrom.py#L253, I noticed that there is no causal mask being applied when computing kernel 1 and kernel 2, which violates the causal condition. Additionally, even though the variables self.causal_mask_1 and self.causal_mask_2 defined earlier are used in those two fuctions, the inclusion of the landmask pooling(https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/nystrom.py#L229)  still allows future tokens to be used in the landmask computation, which also violates the causal condition.

Please correct me if I am wrong. Thank you!

**Comment by blefaudeux** [comment]
hey, sorry for the delay, I think that's related to https://github.com/facebookresearch/xformers/issues/107 and you're correct indeed, causal is not respected. It's been a while (and @dianaml0 was on top of that) but I think that the causality constraint is not completely trivial to pass in Nystrom, due to the pooling. A minima I think that xformers should assert so that causal + Nystrom is not possible, and nobody gets trapped. Else I think that the pooling function for k,q could optionally return the causal mask which matches the pooling. What do you think ?

**Comment by yuzhenmao** [comment]
Thanks for the reply! That makes sense to me.
