### ISSUE TITLE
Xformers binaries do not include arch code for H100s (SM90)

### ISSUE THREAD

**Issue by Skylion007** [facebookresearch/xformers#784]
# 🐛 Bug

## To Reproduce

1. Try xformers on H100s. This is supported according to the release notes, but the feature is experimental.
2. xformers complains that is not built for SM90. This is easily fixed by installing xformers from source. The issue seems to be packaging scripts here: https://github.com/facebookresearch/xformers/blob/b31f4a10209a9878e90d2f5ea5d98857c64a5bc0/packaging/pkg_helpers.bash#L24
3. Workaround is currently to install xformers from source which is very slow and painful. It would be great if the binaries could be updated to include support for H100 TORCH_CUDA_ARCH.

## Expected behavior
Binaries include SM90 arch as well.

**Comment by danthe3rd** [comment]
Hi,
Yes we want to support that in the next release hopefully. 2 things blocking us so far:
- we will need to support cuda 12 for best performance on Sm90 - this has implications on the build process, because cuda 12 binaries won't be compatible with cuda 11.x pytorch maybe..?
- we are limited in terms of space we can use in pypi. Adding an architecture will require more space...
https://github.com/pypi/support/issues/2907

**Comment by Skylion007** [comment]
>we will need to support cuda 12 for best performance on Sm90 - this has implications on the build process, because cuda 12 binaries won't be compatible with cuda 11.x pytorch maybe..?

SM90 works fine on CUDA 11.8
