### ISSUE TITLE
`scaled_dot_product_attention` shouldn't slice `attn_mask`

### ISSUE THREAD

**Issue by fmassa** [facebookresearch/xformers#90]
In https://github.com/facebookresearch/xformers/blob/cc7c8edd6907abdb09d10f60e456e224109a4aca/xformers/components/attention/core.py#L233-L248
the core function `scale_dot_product_attention` was made to accept `attn_masks` which are not of the correct shape.

While this looks like a convenience function, IMO this shouldn't be handled at such a core level as `scaled_dot_product_attention`.
Indeed, this behavior can lead to silent bugs (specially if the current slicing strategy doesn't work, e.g., for images), imposes serious performance penalties (by casting sparse tensors to dense tensors), and as such should be handled at a higher level.

Happy to discuss alternatives

**Comment by blefaudeux** [comment]
yes for the slowness, that was the purpose of the logging.warning, it should not be done ideally. I think that it's a hard tradeoff, on the vision side this probably never happens unless there's a mistake (you should rescale the pictures and be done with it), but on the NLP side it's fairly common with different sentences length. I think that there's value in having something convenient (or a hard crash but with enough explanations and helpers so that it's not a blocker), but it could also be somewhere else in the stack indeed, that's certainly fine by me (also the hard crash + plenty of explanations option)
